### PR TITLE
Create dottedfilter.py

### PR DESCRIPTION
**Pull request by Today100**
So I created a dottedfilter function. It will first extract some essential color from the image itself and then create dots with random color extracted from the image all around the image.

For instance, an image looks like this before:

image

It looks like this after applied the function:
image

The quantity of the dots could be modified.

### CODE REVIEW

**Review by Mindful-Developer — CHANGES_REQUESTED** [review]
Cool filter. Filters need to be a class that inherits from the ImageFilter base class. I'll make an example one asap to show the gist of it.

formatting also doesn't meet pep8 standards. I recommend getting "black" `pip install black` and having it autoformat for you. Binds made a nice script that does it for the entire project in /scripts/

**Comment by Today100** [comment]
> Cool filter. Filters need to be a class that inherits from the ImageFilter base class. I'll make an example one asap to show the gist of it.
> 
> formatting also doesn't meet pep8 standards. I recommend getting "black" `pip install black` and having it autoformat for you. Binds made a nice script that does it for the entire project in /scripts/

I am trying to move it into the class like your example filter. However, right now I faced so many errors I am currently try to solve it. I cannot run the code locally for some problems. It either gives me "No module named 'glitchup' ", or "attempted relative import with no known parent package", or "cannot import name 'TypeAlias' from 'typing' ". Is it okay if I send the class to you to test if it works or if you have any clue on how to solve them?

**Comment by Mindful-Developer** [comment]
Yeah, of course. I just got home from the funeral so I will have to look at it in the morning as I am beat.

**Comment by Today100** [comment]
> Yeah, of course. I just got home from the funeral so I will have to look at it in the morning as I am beat.

That will be awesome!

**Review by Mindful-Developer — APPROVED** [review]
Looks good.

**Review by bindsdev — APPROVED** [review]

**Pull request merged**
