### PR TITLE
Feature/numberfilter

### PR DESCRIPTION
**Pull request by Today100**
A filter that could blur the image and then add zero and one on top.

Before the filter:
image

After the filter:
image

### CODE REVIEW

**Review by Mindful-Developer — COMMENTED** [review]
Hey, this filter is REALLY cool! I have a suggestion to take it up a notch. If you quadruple the amount of numbers and remove the whitespace and get rid of the original picture entirely, you would just be left with the numbers making the image and I think that might make this even better!

**Comment by Today100** [comment]
> Hey, this filter is REALLY cool! I have a suggestion to take it up a notch. If you quadruple the amount of numbers and remove the whitespace and get rid of the original picture entirely, you would just be left with the numbers making the image and I think that might make this even better!

Got it, I will work on that!

**Comment by Mindful-Developer** [comment]
Whoa!!! YES!! This is epic!

**Review by Mindful-Developer — CHANGES_REQUESTED** [review]
Submitted a PR to remove the return statement and adapt the function so that it still produces the awesome output that you created. Once the PR is resolved, I'll drop this and we can merge the filter.

**Review by Mindful-Developer — APPROVED** [review]
Looks awesome!

**Pull request merged**
